-- Create Exam Boards table
create table if not exists exam_boards (
    id bigint generated by default as identity primary key,
    name text not null unique,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Create Exams table
create table if not exists exams (
    id uuid default gen_random_uuid() primary key,
    user_id uuid references auth.users(id) on delete cascade not null,
    board_id bigint references exam_boards(id) on delete set null,
    year integer not null,
    date date not null default current_date,
    title text, -- Optional title (e.g. "Simulado 1")
    created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Create Exam Scores table (Normalization for scores per discipline)
create table if not exists exam_scores (
    id uuid default gen_random_uuid() primary key,
    exam_id uuid references exams(id) on delete cascade not null,
    discipline_id bigint references disciplines(id) on delete cascade not null,
    questions_total integer not null check (questions_total >= 0),
    questions_correct integer not null check (questions_correct >= 0),
    created_at timestamp with time zone default timezone('utc'::text, now()) not null,
    unique(exam_id, discipline_id),
    check (questions_correct <= questions_total)
);

-- RLS Policies

-- Exam Boards (Public read, Authenticated create)
alter table exam_boards enable row level security;

create policy "Boards are viewable by everyone"
    on exam_boards for select
    using (true);

create policy "Authenticated users can create boards"
    on exam_boards for insert
    with check (auth.role() = 'authenticated');

-- Exams (User private)
alter table exams enable row level security;

create policy "Users can view their own exams"
    on exams for select
    using (auth.uid() = user_id);

create policy "Users can insert their own exams"
    on exams for insert
    with check (auth.uid() = user_id);

create policy "Users can update their own exams"
    on exams for update
    using (auth.uid() = user_id);

create policy "Users can delete their own exams"
    on exams for delete
    using (auth.uid() = user_id);

-- Exam Scores (Inherit from Exam via RLS or direct relation check)
alter table exam_scores enable row level security;

create policy "Users can view scores of their exams"
    on exam_scores for select
    using (
        exists (
            select 1 from exams 
            where exams.id = exam_scores.exam_id 
            and exams.user_id = auth.uid()
        )
    );

create policy "Users can insert scores for their exams"
    on exam_scores for insert
    with check (
        exists (
            select 1 from exams 
            where exams.id = exam_scores.exam_id 
            and exams.user_id = auth.uid()
        )
    );

create policy "Users can delete scores of their exams"
    on exam_scores for delete
    using (
        exists (
            select 1 from exams 
            where exams.id = exam_scores.exam_id 
            and exams.user_id = auth.uid()
        )
    );
